spring:
  application:
    # Service ka naam (Eureka me isi naam se register hoga)
    name: ACTIVITY-SERVICE
  config:
    import: optional:configserver:http://configserver:9999

#  rabbitmq:
#    # RabbitMQ server connection details
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  data:
#    mongodb:
#      # MongoDB connection URI
#      uri: mongodb://localhost:27017/fitnessactivity
#
#      # MongoDB database name
#      database: fitnessactivity
#
#server:
#  # Activity service ka port
#  port: 9096
#
#eureka:
#  client:
#    # Eureka server me service register karega
#    register-with-eureka: true
#
#    # Eureka se dusri services ki info lega
#    fetch-registry: true
#
#    service-url:
#      # Eureka server ka address
#      defaultZone: http://localhost:8761/eureka/
#
#rabbitmq:
#  exchange:
#    # Exchange ka naam (producer yahin message bhejega)
#    name: fitness.exchange
#
#  queue:
#    # Queue ka naam (consumer yahin se message consume karega)
#    name: activity.queue
#
#  routing:
#    # Routing key (exchange â†’ queue mapping ke liye)
#    key: activity.tracking
