spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://configserver:9999

#
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#
#        - id: activity-service
#          uri: lb://ACTIVITY-SERVICE
#          predicates:
#            - Path=/api/activities/**
#
#        - id: ai-service
#          uri: lb://AI-SERVICE
#          predicates:
#            - Path=/api/recommendations/**
#
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

