#server:
#  port: 9095

spring:
  application:
    name: USER-SERVICE

#  jwt:
#    secret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2mo




  config:
    import: optional:configserver:http://configserver:9999


#  datasource:
#    url: jdbc:mysql://localhost:3306/fitness_user_db
#    username: root
#    password: Arsh@1106
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
